### ISSUE TITLE
[FEATURE] JS framework wrapper around this library

### ISSUE THREAD

**Issue by MatteuSan** [dev-protocol/hashi#33]
### Detailed description

Make a react, vue, and astro wrapper around Hashi

### Context

To make using the components easier

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatteuSan** [comment]
To add: The wrappers should be in a different repo for each implementation

**Comment by krishguptadev** [comment]
Astro doesn't need a wrapper
